### ISSUE TITLE
Sign up page is potentially broken

### ISSUE THREAD

**Issue by viswavi** [zeno-ml/zeno-hub#450]
When I try to register a new account on the ZenoML Hub, I see no response.
<img width="567" alt="Screenshot 2023-11-17 at 12 50 25 PM" src="https://github.com/zeno-ml/zeno-hub/assets/2577384/52b85c1e-785b-41f0-b854-29f5395de27c">

When I try to log in with the user I attempted to register, it says "User does not exist"
<img width="310" alt="Screenshot 2023-11-17 at 12 50 51 PM" src="https://github.com/zeno-ml/zeno-hub/assets/2577384/1c10025a-8b95-44cd-a60b-ef0e92fbf47c">

**Comment by viswavi** [comment]
Nevermind, just noticed the error at the bottom of the sign up page! I think this can be made more noticeable

**Comment by cabreraalex** [comment]
Ah sorry about that, we can move the error up so it's more visible :)
