### ISSUE TITLE
System outputs not refreshing

### ISSUE THREAD

**Issue by jacobrast** [zeno-ml/zeno-hub#481]
When changing the system on the "Explore your data and system outputs" tab and on the "Qualitatively compare system outputs" tab, the data does not refresh.

See example video: https://github.com/zeno-ml/zeno-hub/assets/5910476/39af744d-370e-4bee-adba-3d642cb65100

System:
MacOS
* Firefox
* Brave
* Chrome

**Comment by Sparkier** [comment]
Hi Jacob, thank you for filing this. I can't reproduce this, unfortunately. Are you experiencing this for all projects?

**Comment by jacobrast** [comment]
Hi, I only have a single project for testing so cannot confirm. However, I am only seeing the issue for data slices with a very large number (>10,000) of entries.

**Comment by Sparkier** [comment]
Thank you, on it.

**Comment by jacobrast** [comment]
It's working!! Thank you!
